services:
  db:
    image: postgres:16-alpine
    container_name: fitness-tracker-db
    environment:
      POSTGRES_DB: fitness_tracker
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: fitnesstracker-app:latest
    container_name: fitness-tracker-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fitness_tracker
      DB_USER: devops
      DB_PASSWORD: password
      JWT_SECRET: fitness-tracker-secret-key-minimum-256-bit-long-string
    depends_on:
      - db

volumes:
  postgres_data: