apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-tracker
  template:
    metadata:
      labels:
        app: fitness-tracker
    spec:
      containers:
        - name: fitness-tracker
          image: mehdi2005/fitness-tracker:latest  # dein Docker Hub Image
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fitness-tracker-config   # alle Werte aus ConfigMap
            - secretRef:
                name: fitness-tracker-secret   # alle Werte aus Secret