apiVersion: v1        # Kubernetes API Version
kind: ConfigMap       # Typ der Ressource → Konfigurationsdaten
metadata:
  name: fitness-tracker-config  # Name der ConfigMap
data:
  # Datenbankverbindung
  # postgres-service → so heißt später unser PostgreSQL Service in Kubernetes
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/fitness_tracker

  # Datenbankbenutzer
  SPRING_DATASOURCE_USERNAME: mehdirahimi

  # JWT Ablaufzeit in Millisekunden (24 Stunden)
  JWT_EXPIRATION: "86400000"