apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1          # nur eine PostgreSQL Instanz
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine  # gleiche Version wie docker-compose
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fitness_tracker
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: fitness-tracker-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fitness-tracker-secret
                  key: SPRING_DATASOURCE_PASSWORD