# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_tracker
spring.datasource.username=mehdirahimi
spring.datasource.password=
# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true